// Broken stdout/stderr pipes (e.g. parent terminal closed) throw EPIPE on console.log
// and Electron shows an "A JavaScript error occurred in the main process" dialog.
function ignoreBrokenPipe(stream: NodeJS.WriteStream | null | undefined) {
  stream?.on?.('error', (err: NodeJS.ErrnoException) => {
    if (err.code === 'EPIPE' || err.code === 'ERR_STREAM_DESTROYED') return;
    throw err;
  });
}
ignoreBrokenPipe(process.stdout);
ignoreBrokenPipe(process.stderr);
process.on('uncaughtException', (err: NodeJS.ErrnoException) => {
  if (err?.code === 'EPIPE' || err?.code === 'ERR_STREAM_DESTROYED') return;
  console.error('Uncaught exception in main process:', err);
});

import { app, BrowserWindow, dialog, ipcMain, nativeImage, shell } from 'electron';
import * as path from 'path';
import * as fsp from 'fs/promises';

console.log('=== MAIN PROCESS STARTING ===');

// Import database with error handling
let database: any;
try {
  const dbModule = require('./main/db/database');
  database = dbModule.database;
  console.log('Database module imported successfully');
} catch (error) {
  console.error('Failed to import database module:', error);
  // Create a mock database object to prevent crashes
  database = {
    initialize: async (): Promise<void> => console.log('Mock database initialized'),
    getOrCreateInstance: async (): Promise<string> => 'mock-guid',
    listUsers: async (): Promise<any[]> => [],
    addUser: async (): Promise<number> => 1,
    updateUser: async (): Promise<void> => {},
    removeUser: async (): Promise<void> => {},
    getUserById: async (): Promise<any> => undefined,
    listFolders: async (): Promise<any[]> => [],
    addFolder: async (): Promise<number> => 1,
    removeFolder: async (): Promise<void> => {},
    updateFolderProperties: async (): Promise<void> => {},
    getFolderByGuid: async (): Promise<any> => null,
    debugDatabase: async (): Promise<any> => ({ error: 'Mock database' }),
    close: async (): Promise<void> => {}
  };
}
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const RTC_SERVER_WEBPACK_ENTRY: string;

import {
  CONNECTION_CONFIG,
  setDevApiEndpoint,
  setDevWebBase,
  setDevSignalingBase,
  getConnectionEndpoint,
  getSignalingBaseUrl,
} from './renderer/config';
// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let mainWindow: BrowserWindow | null = null;
let connectionPollingInterval: NodeJS.Timeout | null = null;
let instanceGuid: string | null = null;

type LiveSession = {
  id: string;
  peerId: string;
  folderId: string;
  folderPath?: string;
  connectedAt: number;
};

const liveSessions = new Map<string, LiveSession>();

function sendToMainWindow(channel: string, payload: unknown) {
  if (!mainWindow || mainWindow.isDestroyed()) return;
  try {
    mainWindow.webContents.send(channel, payload);
  } catch (err) {
    const code = (err as NodeJS.ErrnoException)?.code;
    if (code === 'EPIPE' || code === 'ERR_STREAM_DESTROYED') return;
    console.error(`Failed to send ${channel}:`, err);
  }
}

function notifyStatsUpdated() {
  sendToMainWindow('stats-updated', { at: Date.now() });
}

function listLiveSessions(): LiveSession[] {
  return Array.from(liveSessions.values()).sort(
    (a, b) => b.connectedAt - a.connectedAt
  );
}

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      sandbox: false, // Allow scripts,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {
  try {
    // Initialize database
    await database.initialize();
    console.log('Database initialized successfully');
    
    // Create window after database is ready
    createWindow();
  } catch (error) {
    console.error('Failed to initialize database:', error);
    // Still create window even if database fails
    createWindow();
  }
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

function closeRtcWindow(win: BrowserWindow) {
  if (win.isDestroyed()) return;
  // Detached DevTools become orphan windows unless closed first
  if (win.webContents.isDevToolsOpened()) {
    win.webContents.closeDevTools();
  }
  if (!win.isDestroyed()) {
    win.close();
  }
}

function openRTCWindow(
  peerId: string,
  folderId: string,
  folderPath?: string,
  isPasswordProtected = false
) {
  console.log(`Opening RTC host for folder: ${folderId} (${folderPath || 'path unknown'}), peer: ${peerId}`);

  const sessionId = `${peerId}:${folderId}:${Date.now()}`;
  liveSessions.set(sessionId, {
    id: sessionId,
    peerId,
    folderId,
    folderPath,
    connectedAt: Date.now(),
  });
  notifyStatsUpdated();

  const rtcWindow = new BrowserWindow({
    width: 800,
    height: 600,
    title: `ShareFolder Host - ${folderId}`,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      webSecurity: false,
    },
  });

  rtcWindow.loadURL(RTC_SERVER_WEBPACK_ENTRY);
  rtcWindow.webContents.openDevTools({ mode: 'detach' });

  const clearSession = () => {
    if (liveSessions.delete(sessionId)) {
      notifyStatsUpdated();
    }
  };

  rtcWindow.on('close', () => {
    if (!rtcWindow.isDestroyed() && rtcWindow.webContents.isDevToolsOpened()) {
      rtcWindow.webContents.closeDevTools();
    }
  });
  rtcWindow.on('closed', clearSession);

  rtcWindow.webContents.on('did-fail-load', (_event, errorCode, errorDescription, validatedURL) => {
    console.log(`Failed to load ${validatedURL}: ${errorDescription} (${errorCode})`);
  });

  rtcWindow.webContents.on('did-finish-load', () => {
    console.log('RTC host window loaded');
    rtcWindow.webContents.send('rtc-connection-info', {
      peerId,
      folderId,
      folderPath: folderPath || 'Path not available',
      signalingBaseUrl: getSignalingBaseUrl(),
      isPasswordProtected,
    });
  });
}

// Connection status polling
async function checkConnectionStatus() {
  if (!instanceGuid) return;
  
  try {
    console.log(`🔍 Polling connections for instance: ${instanceGuid}`);
    const response = await fetch(`${getConnectionEndpoint()}?guid=${instanceGuid}`);
    
    if (response.ok) {
      const data = await response.json();
      console.log('✅ Connection response received:', data);
      console.log(data);
      
      // Check for new connections and open RTC windows
      if (data.connections && data.connections.length > 0) {
        console.log(`🔗 Found ${data.connections.length} new connection(s)`);
        data.connections.forEach(async (connection: any) => {
          try {
            try {
              await database.recordConnectionEvent(
                connection.peerId,
                connection.folderId
              );
              notifyStatsUpdated();
            } catch (statsErr) {
              console.error('Failed to record connection event:', statsErr);
            }
            const folder = await database.getFolderByGuid(connection.folderId);
            const folderPath = folder ? folder.path : undefined;
            const isPasswordProtected = Boolean(folder?.isPasswordProtected);
            if (!folderPath) {
              console.log(`Could not get folder path for GUID ${connection.folderId}, opening without path`);
            }
            openRTCWindow(
              connection.peerId,
              connection.folderId,
              folderPath,
              isPasswordProtected
            );
          } catch (error) {
            console.error(`Failed to open RTC for folder ${connection.folderId}:`, error);
            openRTCWindow(connection.peerId, connection.folderId);
          }
        });
      }
      
      // Send connection status update with connections data
      sendToMainWindow('connection-status-update', {
        status: 'connected',
        lastCheck: new Date().toISOString(),
        connections: data.connections || []
      });
    } else {
      console.log(`❌ Connection polling failed with HTTP ${response.status}`);
      sendToMainWindow('connection-status-update', {
        status: 'disconnected',
        lastCheck: new Date().toISOString(),
        error: `HTTP ${response.status}`
      });
    }
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    console.log('💥 Connection polling error:', errorMessage);
    sendToMainWindow('connection-status-update', {
      status: 'error',
      lastCheck: new Date().toISOString(),
      error: errorMessage
    });
  }
}

async function startConnectionPolling(guid: string) {
  try {
    console.log(`🚀 Starting connection polling for GUID: ${guid}`);
    
    // Store the GUID in the database
    await database.getOrCreateInstance();
    instanceGuid = guid;
    
    // Stop existing polling if any
    if (connectionPollingInterval) {
      clearInterval(connectionPollingInterval);
      console.log('🔄 Stopped previous polling interval');
    }
    
    // Initial check
    checkConnectionStatus();
    
    // Start polling
    connectionPollingInterval = setInterval(checkConnectionStatus, CONNECTION_CONFIG.pollInterval);
    console.log(`⏰ Connection polling started with ${CONNECTION_CONFIG.pollInterval}ms interval`);
  } catch (error) {
    console.error('💥 Failed to start connection polling:', error);
  }
}

function stopConnectionPolling() {
  if (connectionPollingInterval) {
    clearInterval(connectionPollingInterval);
    connectionPollingInterval = null;
  }
}



// Register IPC handlers immediately
console.log('Starting to register IPC handlers...');

function readJpegExifOrientation(buf: Buffer): number {
  if (buf.length < 4 || buf[0] !== 0xff || buf[1] !== 0xd8) return 1;
  let offset = 2;
  while (offset + 4 < buf.length) {
    if (buf[offset] !== 0xff) break;
    const marker = buf[offset + 1];
    const size = buf.readUInt16BE(offset + 2);
    if (marker === 0xe1 && size >= 8) {
      const start = offset + 4;
      if (buf.toString('ascii', start, start + 4) !== 'Exif') return 1;
      const tiff = start + 6;
      if (tiff + 8 > buf.length) return 1;
      const little = buf.toString('ascii', tiff, tiff + 2) === 'II';
      const u16 = (o: number) =>
        little ? buf.readUInt16LE(o) : buf.readUInt16BE(o);
      const u32 = (o: number) =>
        little ? buf.readUInt32LE(o) : buf.readUInt32BE(o);
      const ifd0 = tiff + u32(tiff + 4);
      if (ifd0 + 2 > buf.length) return 1;
      const entries = u16(ifd0);
      for (let i = 0; i < entries; i++) {
        const entry = ifd0 + 2 + i * 12;
        if (entry + 12 > buf.length) break;
        if (u16(entry) === 0x0112) {
          return u16(entry + 8) || 1;
        }
      }
      return 1;
    }
    if (marker === 0xda) break;
    offset += 2 + size;
  }
  return 1;
}

function mapBitmap(
  img: Electron.NativeImage,
  width: number,
  height: number,
  map: (
    x: number,
    y: number,
    srcW: number,
    srcH: number
  ) => { x: number; y: number }
): Electron.NativeImage {
  const src = img.toBitmap();
  const srcW = img.getSize().width;
  const srcH = img.getSize().height;
  const dest = Buffer.alloc(width * height * 4);
  for (let y = 0; y < srcH; y++) {
    for (let x = 0; x < srcW; x++) {
      const { x: nx, y: ny } = map(x, y, srcW, srcH);
      const srcIdx = (y * srcW + x) * 4;
      const dstIdx = (ny * width + nx) * 4;
      src.copy(dest, dstIdx, srcIdx, srcIdx + 4);
    }
  }
  return nativeImage.createFromBitmap(dest, { width, height });
}

/** Bake EXIF orientation into pixels so JPEG thumbs match browser/camera view. */
function applyExifOrientation(
  img: Electron.NativeImage,
  orientation: number
): Electron.NativeImage {
  const { width, height } = img.getSize();
  switch (orientation) {
    case 2: // flip horizontal
      return mapBitmap(img, width, height, (x, y, w) => ({
        x: w - 1 - x,
        y,
      }));
    case 3: // 180°
      return mapBitmap(img, width, height, (x, y, w, h) => ({
        x: w - 1 - x,
        y: h - 1 - y,
      }));
    case 4: // flip vertical
      return mapBitmap(img, width, height, (x, y, _w, h) => ({
        x,
        y: h - 1 - y,
      }));
    case 5: // transpose
      return mapBitmap(img, height, width, (x, y) => ({
        x: y,
        y: x,
      }));
    case 6: // 90° CW (common phone portrait)
      return mapBitmap(img, height, width, (x, y, _w, h) => ({
        x: h - 1 - y,
        y: x,
      }));
    case 7: // transverse
      return mapBitmap(img, height, width, (x, y, w, h) => ({
        x: h - 1 - y,
        y: w - 1 - x,
      }));
    case 8: // 90° CCW
      return mapBitmap(img, height, width, (x, y, w) => ({
        x: y,
        y: w - 1 - x,
      }));
    default:
      return img;
  }
}

app.whenReady().then(() => {
  // Configure development API endpoint if in development mode
  if (process.env.NODE_ENV === 'development') {
    const connectionsEndpoint =
      process.env.CONNECTION_ENDPOINT || 'http://localhost:3010/connections';
    setDevApiEndpoint(connectionsEndpoint);
    setDevSignalingBase(
      process.env.SIGNALING_BASE || connectionsEndpoint.replace(/\/connections\/?$/, '')
    );
    setDevWebBase(process.env.WEB_BASE || 'http://localhost:3010');
    console.log(`Development mode: API ${getConnectionEndpoint()}, signaling ${getSignalingBaseUrl()}`);
  }
  
  // IPC: open directory dialog
  ipcMain.handle('select-folder', async () => {
    const res = await dialog.showOpenDialog(mainWindow!, {
      properties: ['openDirectory']
    });
    if (res.canceled || !res.filePaths?.[0]) return null;
    return res.filePaths[0];
  });

  // IPC: open URL in default browser
  ipcMain.handle('open-external', async (event, url: string) => {
    try {
      await shell.openExternal(url);
    } catch (error) {
      console.error('Failed to open external URL:', error);
    }
  });

  // IPC: start connection polling
  ipcMain.handle('start-connection-polling', async (event, guid: string) => {
    startConnectionPolling(guid);
    return { success: true };
  });

  // IPC: handle new connections from renderer
  // Commented out to prevent duplicate RTC windows - API polling handles this
  // ipcMain.on('new-connections', (event, connections: Array<{ peerId: string; folderId: string }>) => {
  //   console.log('🔗 Received new connections from renderer:', connections);
  //   connections.forEach((connection) => {
  //     openRTCWindow(connection.peerId, connection.folderId);
  //   });
  // });

  // Test IPC handler
  ipcMain.handle('test-ping', () => {
    console.log('Test ping handler called');
    return 'pong';
  });

  // Database operations
  console.log('Registering db-get-instance handler...');



  // IPC: stop connection polling
  ipcMain.handle('stop-connection-polling', async () => {
    stopConnectionPolling();
    return { success: true };
  });

  ipcMain.on('close-rtc-window', (event) => {
    const win = BrowserWindow.fromWebContents(event.sender);
    if (win) {
      closeRtcWindow(win);
    }
  });

  // IPC: Database operations
  ipcMain.handle('db-get-instance', async () => {
    try {
      return await database.getOrCreateInstance();
    } catch (error) {
      console.error('Failed to get instance:', error);
      throw error;
    }
  });

  ipcMain.handle('db-list-users', async () => {
    try {
      return await database.listUsers();
    } catch (error) {
      console.error('Failed to list users:', error);
      throw error;
    }
  });

  ipcMain.handle('db-add-user', async (event, userData) => {
    try {
      return await database.addUser(userData);
    } catch (error) {
      console.error('Failed to add user:', error);
      throw error;
    }
  });

  ipcMain.handle('db-update-user', async (event, id: number, updates) => {
    try {
      await database.updateUser(id, updates);
      return { success: true };
    } catch (error) {
      console.error('Failed to update user:', error);
      throw error;
    }
  });

  ipcMain.handle('db-remove-user', async (event, id: number) => {
    try {
      await database.removeUser(id);
      return { success: true };
    } catch (error) {
      console.error('Failed to remove user:', error);
      throw error;
    }
  });

  ipcMain.handle('db-get-user', async (event, id: number) => {
    try {
      return await database.getUserById(id);
    } catch (error) {
      console.error('Failed to get user:', error);
      throw error;
    }
  });

  ipcMain.handle(
    'db-authenticate-user',
    async (_event, email: string, password: string) => {
      try {
        return await database.authenticateUser(email, password);
      } catch (error) {
        console.error('Failed to authenticate user:', error);
        throw error;
      }
    }
  );

  ipcMain.handle('db-list-folders', async () => {
    try {
      return await database.listFolders();
    } catch (error) {
      console.error('Failed to list folders:', error);
      throw error;
    }
  });

  ipcMain.handle('db-add-folder', async (event, path: string, guid?: string) => {
    try {
      return await database.addFolder(path, guid);
    } catch (error) {
      console.error('Failed to add folder:', error);
      throw error;
    }
  });

  ipcMain.handle('db-remove-folder', async (event, id: number) => {
    try {
      await database.removeFolder(id);
      return { success: true };
    } catch (error) {
      console.error('Failed to remove folder:', error);
      throw error;
    }
  });

  ipcMain.handle('db-update-folder', async (event, id: number, updates) => {
    try {
      await database.updateFolderProperties(id, updates);
      return { success: true };
    } catch (error) {
      console.error('Failed to update folder:', error);
      throw error;
    }
  });

  ipcMain.handle('db-get-folder', async (event, guid: string) => {
    try {
      return await database.getFolderByGuid(guid);
    } catch (error) {
      console.error('Failed to get folder:', error);
      throw error;
    }
  });

  ipcMain.handle('db-debug', async () => {
    try {
      return await database.debugDatabase();
    } catch (error) {
      console.error('Failed to debug database:', error);
      throw error;
    }
  });

  ipcMain.handle('db-get-stats-summary', async (_event, days = 14) => {
    try {
      const summary = await database.getStatsSummary(Number(days) || 14);
      const recentActivity = await database.getRecentActivity(60);
      return {
        ...summary,
        liveSessions: listLiveSessions(),
        recentActivity,
      };
    } catch (error) {
      console.error('Failed to get stats summary:', error);
      throw error;
    }
  });

  ipcMain.handle(
    'db-record-download-event',
    async (
      _event,
      folderId: string,
      relativePath: string,
      bytes: number
    ) => {
      try {
        await database.recordDownloadEvent(folderId, relativePath, bytes);
        notifyStatsUpdated();
        return { success: true };
      } catch (error) {
        console.error('Failed to record download event:', error);
        throw error;
      }
    }
  );

  ipcMain.handle(
    'db-record-preview-event',
    async (
      _event,
      folderId: string,
      relativePath: string,
      bytes: number
    ) => {
      try {
        await database.recordPreviewEvent(folderId, relativePath, bytes);
        notifyStatsUpdated();
        return { success: true };
      } catch (error) {
        console.error('Failed to record preview event:', error);
        throw error;
      }
    }
  );

  ipcMain.handle(
    'list-dir',
    async (
      _event,
      folderPath: string,
      relativePath = '',
      offset = 0,
      limit = 100
    ) => {
      const root = path.resolve(folderPath);
      const target = relativePath
        ? path.resolve(root, relativePath)
        : root;
      if (!target.startsWith(root + path.sep) && target !== root) {
        throw new Error('Invalid directory path');
      }

      const pageSize = Math.max(1, Math.min(Number(limit) || 100, 200));
      const start = Math.max(0, Number(offset) || 0);

      const dirents = await fsp.readdir(target, { withFileTypes: true });
      const catalog: Array<{ name: string; type: 'file' | 'dir' }> = [];

      for (const entry of dirents) {
        if (entry.name.startsWith('.')) continue;
        if (entry.isDirectory()) {
          catalog.push({ name: entry.name, type: 'dir' });
        } else if (entry.isFile()) {
          catalog.push({ name: entry.name, type: 'file' });
        }
      }

      catalog.sort((a, b) => {
        if (a.type !== b.type) return a.type === 'dir' ? -1 : 1;
        return a.name.localeCompare(b.name);
      });

      const total = catalog.length;
      const slice = catalog.slice(start, start + pageSize);
      const entries: Array<{
        name: string;
        type: 'file' | 'dir';
        size?: number;
        relativePath: string;
      }> = [];

      for (const item of slice) {
        const rel = relativePath ? `${relativePath}/${item.name}` : item.name;
        if (item.type === 'dir') {
          entries.push({ name: item.name, type: 'dir', relativePath: rel });
        } else {
          const stat = await fsp.stat(path.join(target, item.name));
          entries.push({
            name: item.name,
            type: 'file',
            size: stat.size,
            relativePath: rel,
          });
        }
      }

      return {
        entries,
        offset: start,
        limit: pageSize,
        total,
        hasMore: start + entries.length < total,
      };
    }
  );

  ipcMain.handle(
    'read-file-range',
    async (
      _event,
      folderPath: string,
      relativePath: string,
      start: number,
      end: number
    ) => {
      const root = path.resolve(folderPath);
      const fullPath = path.resolve(root, relativePath);
      if (!fullPath.startsWith(root + path.sep) && fullPath !== root) {
        throw new Error('Invalid file path');
      }
      const length = Math.max(0, end - start);
      const fd = await fsp.open(fullPath, 'r');
      try {
        const buffer = Buffer.alloc(length);
        const { bytesRead } = await fd.read(buffer, 0, length, start);
        return buffer.subarray(0, bytesRead).buffer.slice(
          buffer.byteOffset,
          buffer.byteOffset + bytesRead
        );
      } finally {
        await fd.close();
      }
    }
  );

  ipcMain.handle(
    'get-image-thumbnail',
    async (
      _event,
      folderPath: string,
      relativePath: string,
      maxWidth = 512
    ): Promise<ArrayBuffer | null> => {
      const root = path.resolve(folderPath);
      const fullPath = path.resolve(root, relativePath);
      if (!fullPath.startsWith(root + path.sep) && fullPath !== root) {
        throw new Error('Invalid file path');
      }

      const fileBuf = await fsp.readFile(fullPath);
      let img = nativeImage.createFromBuffer(fileBuf);
      if (img.isEmpty()) {
        return null;
      }

      const orientation = readJpegExifOrientation(fileBuf);
      if (orientation !== 1) {
        img = applyExifOrientation(img, orientation);
      }

      const { width } = img.getSize();
      const targetWidth = Math.max(1, Math.floor(Number(maxWidth) || 512));
      // Never upscale: only shrink when wider than the requested max.
      const outputWidth = Math.min(width, targetWidth);
      const output =
        outputWidth < width
          ? img.resize({ width: outputWidth, quality: 'best' })
          : img;

      const jpeg = output.toJPEG(82);
      return jpeg.buffer.slice(
        jpeg.byteOffset,
        jpeg.byteOffset + jpeg.byteLength
      );
    }
  );

  // App is ready, but IPC handlers are already registered
  console.log('IPC handlers registered successfully');
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});

// Cleanup on app quit
app.on('before-quit', async () => {
  stopConnectionPolling();
  try {
    await database.close();
  } catch (error) {
    console.error('Failed to close database:', error);
  }
});