import { app, BrowserWindow, dialog, ipcMain, shell } from 'electron';
import * as path from 'path';

console.log('=== MAIN PROCESS STARTING ===');

// Import database with error handling
let database: any;
try {
  const dbModule = require('./main/db/database');
  database = dbModule.database;
  console.log('Database module imported successfully');
} catch (error) {
  console.error('Failed to import database module:', error);
  // Create a mock database object to prevent crashes
  database = {
    initialize: async (): Promise<void> => console.log('Mock database initialized'),
    getOrCreateInstance: async (): Promise<string> => 'mock-guid',
    listUsers: async (): Promise<any[]> => [],
    addUser: async (): Promise<number> => 1,
    updateUser: async (): Promise<void> => {},
    removeUser: async (): Promise<void> => {},
    getUserById: async (): Promise<any> => undefined,
    listFolders: async (): Promise<any[]> => [],
    addFolder: async (): Promise<number> => 1,
    removeFolder: async (): Promise<void> => {},
    updateFolderProperties: async (): Promise<void> => {},
    getFolderByGuid: async (): Promise<any> => null,
    debugDatabase: async (): Promise<any> => ({ error: 'Mock database' }),
    close: async (): Promise<void> => {}
  };
}
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const RTC_SERVER_WEBPACK_ENTRY: string;

import {
  CONNECTION_CONFIG,
  setDevApiEndpoint,
  setDevWebBase,
  setDevSignalingBase,
  getConnectionEndpoint,
  getSignalingBaseUrl,
} from './renderer/config';
import * as fsp from 'fs/promises';
// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let mainWindow: BrowserWindow | null = null;
let connectionPollingInterval: NodeJS.Timeout | null = null;
let instanceGuid: string | null = null;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      sandbox: false, // Allow scripts,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {
  try {
    // Initialize database
    await database.initialize();
    console.log('Database initialized successfully');
    
    // Create window after database is ready
    createWindow();
  } catch (error) {
    console.error('Failed to initialize database:', error);
    // Still create window even if database fails
    createWindow();
  }
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

function openRTCWindow(peerId: string, folderId: string, folderPath?: string) {
  console.log(`Opening RTC host for folder: ${folderId} (${folderPath || 'path unknown'}), peer: ${peerId}`);

  const rtcWindow = new BrowserWindow({
    width: 800,
    height: 600,
    title: `ShareFolder Host - ${folderId}`,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      webSecurity: false,
    },
  });

  rtcWindow.loadURL(RTC_SERVER_WEBPACK_ENTRY);
  rtcWindow.webContents.openDevTools({ mode: 'detach' });

  rtcWindow.webContents.on('did-fail-load', (_event, errorCode, errorDescription, validatedURL) => {
    console.log(`Failed to load ${validatedURL}: ${errorDescription} (${errorCode})`);
  });

  rtcWindow.webContents.on('did-finish-load', () => {
    console.log('RTC host window loaded');
    rtcWindow.webContents.send('rtc-connection-info', {
      peerId,
      folderId,
      folderPath: folderPath || 'Path not available',
      signalingBaseUrl: getSignalingBaseUrl(),
    });
  });
}

// Connection status polling
async function checkConnectionStatus() {
  if (!instanceGuid) return;
  
  try {
    console.log(`🔍 Polling connections for instance: ${instanceGuid}`);
    const response = await fetch(`${getConnectionEndpoint()}?guid=${instanceGuid}`);
    
    if (response.ok) {
      const data = await response.json();
      console.log('✅ Connection response received:', data);
      console.log(data);
      
      // Check for new connections and open RTC windows
      if (data.connections && data.connections.length > 0) {
        console.log(`🔗 Found ${data.connections.length} new connection(s)`);
        data.connections.forEach(async (connection: any) => {
          try {
            const folder = await database.getFolderByGuid(connection.folderId);
            const folderPath = folder ? folder.path : undefined;
            if (!folderPath) {
              console.log(`Could not get folder path for GUID ${connection.folderId}, opening without path`);
            }
            openRTCWindow(connection.peerId, connection.folderId, folderPath);
          } catch (error) {
            console.error(`Failed to open RTC for folder ${connection.folderId}:`, error);
            openRTCWindow(connection.peerId, connection.folderId);
          }
        });
      }
      
      // Send connection status update with connections data
      mainWindow?.webContents.send('connection-status-update', {
        status: 'connected',
        lastCheck: new Date().toISOString(),
        connections: data.connections || []
      });
    } else {
      console.log(`❌ Connection polling failed with HTTP ${response.status}`);
      mainWindow?.webContents.send('connection-status-update', {
        status: 'disconnected',
        lastCheck: new Date().toISOString(),
        error: `HTTP ${response.status}`
      });
    }
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    console.log('💥 Connection polling error:', errorMessage);
    mainWindow?.webContents.send('connection-status-update', {
      status: 'error',
      lastCheck: new Date().toISOString(),
      error: errorMessage
    });
  }
}

async function startConnectionPolling(guid: string) {
  try {
    console.log(`🚀 Starting connection polling for GUID: ${guid}`);
    
    // Store the GUID in the database
    await database.getOrCreateInstance();
    instanceGuid = guid;
    
    // Stop existing polling if any
    if (connectionPollingInterval) {
      clearInterval(connectionPollingInterval);
      console.log('🔄 Stopped previous polling interval');
    }
    
    // Initial check
    checkConnectionStatus();
    
    // Start polling
    connectionPollingInterval = setInterval(checkConnectionStatus, CONNECTION_CONFIG.pollInterval);
    console.log(`⏰ Connection polling started with ${CONNECTION_CONFIG.pollInterval}ms interval`);
  } catch (error) {
    console.error('💥 Failed to start connection polling:', error);
  }
}

function stopConnectionPolling() {
  if (connectionPollingInterval) {
    clearInterval(connectionPollingInterval);
    connectionPollingInterval = null;
  }
}



// Register IPC handlers immediately
console.log('Starting to register IPC handlers...');

app.whenReady().then(() => {
  // Configure development API endpoint if in development mode
  if (process.env.NODE_ENV === 'development') {
    const connectionsEndpoint =
      process.env.CONNECTION_ENDPOINT || 'http://localhost:3001/connections';
    setDevApiEndpoint(connectionsEndpoint);
    setDevSignalingBase(
      process.env.SIGNALING_BASE || connectionsEndpoint.replace(/\/connections\/?$/, '')
    );
    setDevWebBase(process.env.WEB_BASE || 'http://localhost:3010');
    console.log(`Development mode: API ${getConnectionEndpoint()}, signaling ${getSignalingBaseUrl()}`);
  }
  
  // IPC: open directory dialog
  ipcMain.handle('select-folder', async () => {
    const res = await dialog.showOpenDialog(mainWindow!, {
      properties: ['openDirectory']
    });
    if (res.canceled || !res.filePaths?.[0]) return null;
    return res.filePaths[0];
  });

  // IPC: open URL in default browser
  ipcMain.handle('open-external', async (event, url: string) => {
    try {
      await shell.openExternal(url);
    } catch (error) {
      console.error('Failed to open external URL:', error);
    }
  });

  // IPC: start connection polling
  ipcMain.handle('start-connection-polling', async (event, guid: string) => {
    startConnectionPolling(guid);
    return { success: true };
  });

  // IPC: handle new connections from renderer
  // Commented out to prevent duplicate RTC windows - API polling handles this
  // ipcMain.on('new-connections', (event, connections: Array<{ peerId: string; folderId: string }>) => {
  //   console.log('🔗 Received new connections from renderer:', connections);
  //   connections.forEach((connection) => {
  //     openRTCWindow(connection.peerId, connection.folderId);
  //   });
  // });

  // Test IPC handler
  ipcMain.handle('test-ping', () => {
    console.log('Test ping handler called');
    return 'pong';
  });

  // Database operations
  console.log('Registering db-get-instance handler...');



  // IPC: stop connection polling
  ipcMain.handle('stop-connection-polling', async () => {
    stopConnectionPolling();
    return { success: true };
  });

  // IPC: Database operations
  ipcMain.handle('db-get-instance', async () => {
    try {
      return await database.getOrCreateInstance();
    } catch (error) {
      console.error('Failed to get instance:', error);
      throw error;
    }
  });

  ipcMain.handle('db-list-users', async () => {
    try {
      return await database.listUsers();
    } catch (error) {
      console.error('Failed to list users:', error);
      throw error;
    }
  });

  ipcMain.handle('db-add-user', async (event, userData) => {
    try {
      return await database.addUser(userData);
    } catch (error) {
      console.error('Failed to add user:', error);
      throw error;
    }
  });

  ipcMain.handle('db-update-user', async (event, id: number, updates) => {
    try {
      await database.updateUser(id, updates);
      return { success: true };
    } catch (error) {
      console.error('Failed to update user:', error);
      throw error;
    }
  });

  ipcMain.handle('db-remove-user', async (event, id: number) => {
    try {
      await database.removeUser(id);
      return { success: true };
    } catch (error) {
      console.error('Failed to remove user:', error);
      throw error;
    }
  });

  ipcMain.handle('db-get-user', async (event, id: number) => {
    try {
      return await database.getUserById(id);
    } catch (error) {
      console.error('Failed to get user:', error);
      throw error;
    }
  });

  ipcMain.handle('db-list-folders', async () => {
    try {
      return await database.listFolders();
    } catch (error) {
      console.error('Failed to list folders:', error);
      throw error;
    }
  });

  ipcMain.handle('db-add-folder', async (event, path: string, guid?: string) => {
    try {
      return await database.addFolder(path, guid);
    } catch (error) {
      console.error('Failed to add folder:', error);
      throw error;
    }
  });

  ipcMain.handle('db-remove-folder', async (event, id: number) => {
    try {
      await database.removeFolder(id);
      return { success: true };
    } catch (error) {
      console.error('Failed to remove folder:', error);
      throw error;
    }
  });

  ipcMain.handle('db-update-folder', async (event, id: number, updates) => {
    try {
      await database.updateFolderProperties(id, updates);
      return { success: true };
    } catch (error) {
      console.error('Failed to update folder:', error);
      throw error;
    }
  });

  ipcMain.handle('db-get-folder', async (event, guid: string) => {
    try {
      return await database.getFolderByGuid(guid);
    } catch (error) {
      console.error('Failed to get folder:', error);
      throw error;
    }
  });

  ipcMain.handle('db-debug', async () => {
    try {
      return await database.debugDatabase();
    } catch (error) {
      console.error('Failed to debug database:', error);
      throw error;
    }
  });

  ipcMain.handle(
    'list-dir',
    async (
      _event,
      folderPath: string,
      relativePath = '',
      offset = 0,
      limit = 100
    ) => {
      const root = path.resolve(folderPath);
      const target = relativePath
        ? path.resolve(root, relativePath)
        : root;
      if (!target.startsWith(root + path.sep) && target !== root) {
        throw new Error('Invalid directory path');
      }

      const pageSize = Math.max(1, Math.min(Number(limit) || 100, 200));
      const start = Math.max(0, Number(offset) || 0);

      const dirents = await fsp.readdir(target, { withFileTypes: true });
      const catalog: Array<{ name: string; type: 'file' | 'dir' }> = [];

      for (const entry of dirents) {
        if (entry.name.startsWith('.')) continue;
        if (entry.isDirectory()) {
          catalog.push({ name: entry.name, type: 'dir' });
        } else if (entry.isFile()) {
          catalog.push({ name: entry.name, type: 'file' });
        }
      }

      catalog.sort((a, b) => {
        if (a.type !== b.type) return a.type === 'dir' ? -1 : 1;
        return a.name.localeCompare(b.name);
      });

      const total = catalog.length;
      const slice = catalog.slice(start, start + pageSize);
      const entries: Array<{
        name: string;
        type: 'file' | 'dir';
        size?: number;
        relativePath: string;
      }> = [];

      for (const item of slice) {
        const rel = relativePath ? `${relativePath}/${item.name}` : item.name;
        if (item.type === 'dir') {
          entries.push({ name: item.name, type: 'dir', relativePath: rel });
        } else {
          const stat = await fsp.stat(path.join(target, item.name));
          entries.push({
            name: item.name,
            type: 'file',
            size: stat.size,
            relativePath: rel,
          });
        }
      }

      return {
        entries,
        offset: start,
        limit: pageSize,
        total,
        hasMore: start + entries.length < total,
      };
    }
  );

  ipcMain.handle(
    'read-file-range',
    async (
      _event,
      folderPath: string,
      relativePath: string,
      start: number,
      end: number
    ) => {
      const root = path.resolve(folderPath);
      const fullPath = path.resolve(root, relativePath);
      if (!fullPath.startsWith(root + path.sep) && fullPath !== root) {
        throw new Error('Invalid file path');
      }
      const length = Math.max(0, end - start);
      const fd = await fsp.open(fullPath, 'r');
      try {
        const buffer = Buffer.alloc(length);
        const { bytesRead } = await fd.read(buffer, 0, length, start);
        return buffer.subarray(0, bytesRead).buffer.slice(
          buffer.byteOffset,
          buffer.byteOffset + bytesRead
        );
      } finally {
        await fd.close();
      }
    }
  );

  // App is ready, but IPC handlers are already registered
  console.log('IPC handlers registered successfully');
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});

// Cleanup on app quit
app.on('before-quit', async () => {
  stopConnectionPolling();
  try {
    await database.close();
  } catch (error) {
    console.error('Failed to close database:', error);
  }
});